// BODY_DATA — 28 těles, česká edukační data pro detail view info panel.
// Zdroje: NASA Solar System Exploration + cs.wikipedia.org (psáno ručně, 2026-04).
// Hodnoty jsou reprezentativní / zaokrouhlené pro čitelnost, ne přesné na desetinné místo.

export const BODY_DATA = {
  sun: {
    name: 'Slunce',
    kind: 'sun',
    tagline: 'Hvězda hlavní posloupnosti, střed naší soustavy.',
    fields: [
      { label: 'Průměr', value: '1 392 700 km (109× Země)' },
      { label: 'Hmota', value: '1,99×10³⁰ kg (333 000× Země)' },
      { label: 'Povrchová teplota', value: '~5 500 °C' },
      { label: 'Teplota jádra', value: '~15 milionů °C' },
      { label: 'Stáří', value: '~4,6 miliardy let' },
      { label: 'Rotační perioda (rovník)', value: '25 dní' },
      { label: 'Složení', value: '73 % vodík, 25 % helium' },
      { label: 'Vzdálenost od Země', value: '149,6 mil. km (1 AU)' },
      { label: 'Sluneční cyklus', value: '~11 let (skvrny)' },
    ],
    funFact: 'Světlo ze Slunce k nám letí 8 minut a 20 sekund — když se Slunce právě podívalo, na Zemi ještě svítí jeho minulost.',
  },

  mercury: {
    name: 'Merkur',
    kind: 'planet',
    tagline: 'Nejmenší a nejbližší planeta Slunci.',
    fields: [
      { label: 'Průměr', value: '4 879 km' },
      { label: 'Hmota', value: '3,30×10²³ kg (0,055× Země)' },
      { label: 'Den', value: '58,6 pozemských dní' },
      { label: 'Rok', value: '88 pozemských dní' },
      { label: 'Počet měsíců', value: '0' },
      { label: 'Atmosféra', value: 'prakticky žádná' },
      { label: 'Povrchová teplota', value: '−173 až +427 °C' },
      { label: 'Gravitace', value: '3,7 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '57,9 mil. km' },
    ],
    funFact: 'Den na Merkuru trvá dvakrát déle než jeho rok — než se jednou otočí kolem osy, stihne dvakrát oběhnout Slunce.',
  },

  venus: {
    name: 'Venuše',
    kind: 'planet',
    tagline: 'Nejteplejší planeta, skleníkové peklo.',
    fields: [
      { label: 'Průměr', value: '12 104 km' },
      { label: 'Hmota', value: '4,87×10²⁴ kg (0,815× Země)' },
      { label: 'Den', value: '243 pozemských dní (retrográdně)' },
      { label: 'Rok', value: '225 pozemských dní' },
      { label: 'Počet měsíců', value: '0' },
      { label: 'Atmosféra', value: 'CO₂ 96 %, dusík 3 %' },
      { label: 'Povrchová teplota', value: '~462 °C' },
      { label: 'Gravitace', value: '8,87 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '108,2 mil. km' },
    ],
    funFact: 'Na Venuši Slunce vychází na západě a zapadá na východě — planeta se otáčí opačným směrem než ostatní.',
  },

  earth: {
    name: 'Země',
    kind: 'planet',
    tagline: 'Modrá planeta, jediný známý domov života.',
    fields: [
      { label: 'Průměr', value: '12 742 km' },
      { label: 'Hmota', value: '5,97×10²⁴ kg' },
      { label: 'Den', value: '24 hodin' },
      { label: 'Rok', value: '365,25 dne' },
      { label: 'Počet měsíců', value: '1 (Luna)' },
      { label: 'Atmosféra', value: '78 % dusík, 21 % kyslík' },
      { label: 'Povrchová teplota', value: '−89 až +58 °C (průměr 15 °C)' },
      { label: 'Gravitace', value: '9,81 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '149,6 mil. km (1 AU)' },
    ],
    funFact: '71 % zemského povrchu pokrývá voda, ale jen 3 % jsou sladká — a většina té je zamrzlá v ledovcích.',
  },

  mars: {
    name: 'Mars',
    kind: 'planet',
    tagline: 'Rudá planeta, kandidát na kolonizaci.',
    fields: [
      { label: 'Průměr', value: '6 779 km' },
      { label: 'Hmota', value: '6,42×10²³ kg (0,107× Země)' },
      { label: 'Den', value: '24 h 37 min' },
      { label: 'Rok', value: '687 pozemských dní' },
      { label: 'Počet měsíců', value: '2 (Phobos, Deimos)' },
      { label: 'Atmosféra', value: 'CO₂ 95 %, velmi řídká' },
      { label: 'Povrchová teplota', value: '−140 až +20 °C' },
      { label: 'Gravitace', value: '3,71 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '227,9 mil. km' },
    ],
    funFact: 'Olympus Mons na Marsu je nejvyšší známá hora sluneční soustavy — 22 km vysoká, třikrát vyšší než Everest.',
  },

  jupiter: {
    name: 'Jupiter',
    kind: 'planet',
    tagline: 'Plynný obr, největší planeta soustavy.',
    fields: [
      { label: 'Průměr', value: '139 820 km (11× Země)' },
      { label: 'Hmota', value: '1,90×10²⁷ kg (318× Země)' },
      { label: 'Den', value: '9 h 56 min' },
      { label: 'Rok', value: '11,86 let' },
      { label: 'Počet měsíců', value: '95 známých (4 hlavní galilejské)' },
      { label: 'Atmosféra', value: 'vodík 90 %, helium 10 %' },
      { label: 'Povrchová teplota', value: '−145 °C (vrchol mraků)' },
      { label: 'Gravitace', value: '24,8 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '778,3 mil. km' },
    ],
    funFact: 'Velká rudá skvrna je bouře větší než Země, která zuří už přes 350 let.',
  },

  saturn: {
    name: 'Saturn',
    kind: 'planet',
    tagline: 'Plynný obr s ikonickými prstenci z ledu.',
    fields: [
      { label: 'Průměr', value: '116 460 km' },
      { label: 'Hmota', value: '5,68×10²⁶ kg (95× Země)' },
      { label: 'Den', value: '10 h 42 min' },
      { label: 'Rok', value: '29,5 let' },
      { label: 'Počet měsíců', value: '146 známých (Titan největší)' },
      { label: 'Atmosféra', value: 'vodík 96 %, helium 3 %' },
      { label: 'Povrchová teplota', value: '−178 °C' },
      { label: 'Gravitace', value: '10,4 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '1,43 mld. km' },
    ],
    funFact: 'Saturn je tak málo hustý, že by na dostatečně velikém oceánu plaval — je lehčí než voda.',
  },

  uranus: {
    name: 'Uran',
    kind: 'planet',
    tagline: 'Ledový obr, který leží na boku.',
    fields: [
      { label: 'Průměr', value: '50 724 km' },
      { label: 'Hmota', value: '8,68×10²⁵ kg (14,5× Země)' },
      { label: 'Den', value: '17 h 14 min (retrográdně)' },
      { label: 'Rok', value: '84 let' },
      { label: 'Počet měsíců', value: '28 známých' },
      { label: 'Atmosféra', value: 'vodík, helium, metan' },
      { label: 'Povrchová teplota', value: '−224 °C' },
      { label: 'Gravitace', value: '8,87 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '2,87 mld. km' },
    ],
    funFact: 'Uran rotuje téměř přesně na boku — jeho osa je nakloněná 98°, takže na pólech trvá léto 42 pozemských let.',
  },

  neptune: {
    name: 'Neptun',
    kind: 'planet',
    tagline: 'Nejvzdálenější planeta, nejsilnější větry.',
    fields: [
      { label: 'Průměr', value: '49 244 km' },
      { label: 'Hmota', value: '1,02×10²⁶ kg (17× Země)' },
      { label: 'Den', value: '16 hodin' },
      { label: 'Rok', value: '165 let' },
      { label: 'Počet měsíců', value: '16 známých (Triton největší)' },
      { label: 'Atmosféra', value: 'vodík, helium, metan' },
      { label: 'Povrchová teplota', value: '−218 °C' },
      { label: 'Gravitace', value: '11,15 m/s²' },
      { label: 'Vzdálenost od Slunce', value: '4,50 mld. km' },
    ],
    funFact: 'Větry na Neptunu dosahují 2 100 km/h — nejrychlejší v celé sluneční soustavě, přestože je nejdál od Slunce.',
  },

  luna: {
    name: 'Luna',
    kind: 'moon',
    tagline: 'Jediný přirozený měsíc Země.',
    fields: [
      { label: 'Průměr', value: '3 474 km' },
      { label: 'Hmota', value: '7,35×10²² kg' },
      { label: 'Den', value: '27,3 pozemských dní (tidálně zamčeno)' },
      { label: 'Vzdálenost od Země', value: '384 400 km' },
      { label: 'Atmosféra', value: 'prakticky žádná' },
      { label: 'Povrchová teplota', value: '−173 až +127 °C' },
      { label: 'Gravitace', value: '1,62 m/s²' },
      { label: 'Mateřská planeta', value: 'Země' },
      { label: 'Objevitel', value: 'pozorovaná od pravěku' },
    ],
    funFact: 'Luna se od Země vzdaluje o 3,8 cm ročně — když vymřeli dinosauři, byla o 2,5 km blíž než dnes.',
  },

  phobos: {
    name: 'Phobos',
    kind: 'moon',
    tagline: 'Větší a bližší z marsovských měsíčků.',
    fields: [
      { label: 'Průměr', value: '22 km' },
      { label: 'Hmota', value: '1,07×10¹⁶ kg' },
      { label: 'Den', value: '7 h 39 min (tidálně zamčeno)' },
      { label: 'Vzdálenost od Marsu', value: '9 376 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '~−40 °C' },
      { label: 'Gravitace', value: '0,0057 m/s²' },
      { label: 'Mateřská planeta', value: 'Mars' },
      { label: 'Objevitel', value: 'Asaph Hall, 1877' },
    ],
    funFact: 'Phobos spadne za 50 milionů let na Mars — jeho orbita se spirálou blíží k planetě.',
  },

  deimos: {
    name: 'Deimos',
    kind: 'moon',
    tagline: 'Menší a vzdálenější marsovský měsíc.',
    fields: [
      { label: 'Průměr', value: '12 km' },
      { label: 'Hmota', value: '1,48×10¹⁵ kg' },
      { label: 'Den', value: '30 h (tidálně zamčeno)' },
      { label: 'Vzdálenost od Marsu', value: '23 463 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '~−40 °C' },
      { label: 'Gravitace', value: '0,003 m/s²' },
      { label: 'Mateřská planeta', value: 'Mars' },
      { label: 'Objevitel', value: 'Asaph Hall, 1877' },
    ],
    funFact: 'Z Marsu by Deimos vypadal jako jasná hvězda — je příliš malý, aby byl vidět jako kotouč pouhým okem.',
  },

  io: {
    name: 'Io',
    kind: 'moon',
    tagline: 'Nejvulkaničtější těleso sluneční soustavy.',
    fields: [
      { label: 'Průměr', value: '3 643 km' },
      { label: 'Hmota', value: '8,93×10²² kg' },
      { label: 'Den', value: '1,77 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Jupiteru', value: '421 700 km' },
      { label: 'Atmosféra', value: 'SO₂, velmi řídká' },
      { label: 'Povrchová teplota', value: '−143 °C (sopky +1 600 °C)' },
      { label: 'Gravitace', value: '1,80 m/s²' },
      { label: 'Mateřská planeta', value: 'Jupiter' },
      { label: 'Objevitel', value: 'Galileo Galilei, 1610' },
    ],
    funFact: 'Io má přes 400 aktivních sopek a její povrch mění každou erupci — nejsou na něm žádné meteorické krátery, všechny byly už přelity lávou.',
  },

  europa: {
    name: 'Europa',
    kind: 'moon',
    tagline: 'Ledový měsíc s oceánem pod krustou.',
    fields: [
      { label: 'Průměr', value: '3 122 km' },
      { label: 'Hmota', value: '4,80×10²² kg' },
      { label: 'Den', value: '3,55 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Jupiteru', value: '671 034 km' },
      { label: 'Atmosféra', value: 'kyslík, velmi řídká' },
      { label: 'Povrchová teplota', value: '−160 °C' },
      { label: 'Gravitace', value: '1,31 m/s²' },
      { label: 'Mateřská planeta', value: 'Jupiter' },
      { label: 'Objevitel', value: 'Galileo Galilei, 1610' },
    ],
    funFact: 'Pod ledovou slupkou Europy je oceán tekuté vody — možná obsahuje dvakrát víc vody než všechny pozemské oceány dohromady.',
  },

  ganymede: {
    name: 'Ganymede',
    kind: 'moon',
    tagline: 'Největší měsíc sluneční soustavy.',
    fields: [
      { label: 'Průměr', value: '5 268 km (větší než Merkur)' },
      { label: 'Hmota', value: '1,48×10²³ kg' },
      { label: 'Den', value: '7,15 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Jupiteru', value: '1 070 400 km' },
      { label: 'Atmosféra', value: 'řídký kyslík' },
      { label: 'Povrchová teplota', value: '−163 °C' },
      { label: 'Gravitace', value: '1,43 m/s²' },
      { label: 'Mateřská planeta', value: 'Jupiter' },
      { label: 'Objevitel', value: 'Galileo Galilei, 1610' },
    ],
    funFact: 'Ganymede je jediný měsíc s vlastním magnetickým polem — a pravděpodobně má pod ledem podpovrchový oceán.',
  },

  callisto: {
    name: 'Callisto',
    kind: 'moon',
    tagline: 'Nejstarší povrch ve sluneční soustavě.',
    fields: [
      { label: 'Průměr', value: '4 820 km' },
      { label: 'Hmota', value: '1,08×10²³ kg' },
      { label: 'Den', value: '16,7 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Jupiteru', value: '1 882 700 km' },
      { label: 'Atmosféra', value: 'CO₂, velmi řídká' },
      { label: 'Povrchová teplota', value: '−139 °C' },
      { label: 'Gravitace', value: '1,24 m/s²' },
      { label: 'Mateřská planeta', value: 'Jupiter' },
      { label: 'Objevitel', value: 'Galileo Galilei, 1610' },
    ],
    funFact: 'Callisto má nejhustěji pokrátrovaný povrch ve sluneční soustavě — je jako kosmický záznamník historie.',
  },

  titan: {
    name: 'Titan',
    kind: 'moon',
    tagline: 'Měsíc s hustou atmosférou a metanovými jezery.',
    fields: [
      { label: 'Průměr', value: '5 150 km' },
      { label: 'Hmota', value: '1,35×10²³ kg' },
      { label: 'Den', value: '15,9 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Saturnu', value: '1 221 870 km' },
      { label: 'Atmosféra', value: 'dusík 94 %, metan 6 %' },
      { label: 'Povrchová teplota', value: '−179 °C' },
      { label: 'Gravitace', value: '1,35 m/s²' },
      { label: 'Mateřská planeta', value: 'Saturn' },
      { label: 'Objevitel', value: 'Christiaan Huygens, 1655' },
    ],
    funFact: 'Na Titanu prší metan — má jezera a řeky z tekutých uhlovodíků, jediné stabilní povrchové tekutiny mimo Zemi.',
  },

  rhea: {
    name: 'Rhea',
    kind: 'moon',
    tagline: 'Druhý největší saturnův měsíc.',
    fields: [
      { label: 'Průměr', value: '1 527 km' },
      { label: 'Hmota', value: '2,31×10²¹ kg' },
      { label: 'Den', value: '4,52 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Saturnu', value: '527 108 km' },
      { label: 'Atmosféra', value: 'velmi řídká (kyslík, CO₂)' },
      { label: 'Povrchová teplota', value: '−174 °C' },
      { label: 'Gravitace', value: '0,26 m/s²' },
      { label: 'Mateřská planeta', value: 'Saturn' },
      { label: 'Objevitel', value: 'Giovanni Cassini, 1672' },
    ],
    funFact: 'Rhea je pravděpodobně jediný známý měsíc s vlastními prstenci — slabé, ale detekovatelné.',
  },

  iapetus: {
    name: 'Iapetus',
    kind: 'moon',
    tagline: 'Měsíc se dvěma tvářemi — jednou černou, druhou bílou.',
    fields: [
      { label: 'Průměr', value: '1 470 km' },
      { label: 'Hmota', value: '1,81×10²¹ kg' },
      { label: 'Den', value: '79,3 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Saturnu', value: '3 560 820 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '−143 °C' },
      { label: 'Gravitace', value: '0,22 m/s²' },
      { label: 'Mateřská planeta', value: 'Saturn' },
      { label: 'Objevitel', value: 'Giovanni Cassini, 1671' },
    ],
    funFact: 'Iapetus má rovníkový hřeben vysoký 20 km, který obtáčí téměř celou polokouli — nikdo neví, jak vznikl.',
  },

  dione: {
    name: 'Dione',
    kind: 'moon',
    tagline: 'Ledový saturnův měsíc s útesy.',
    fields: [
      { label: 'Průměr', value: '1 123 km' },
      { label: 'Hmota', value: '1,10×10²¹ kg' },
      { label: 'Den', value: '2,74 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Saturnu', value: '377 396 km' },
      { label: 'Atmosféra', value: 'stopově kyslík' },
      { label: 'Povrchová teplota', value: '−186 °C' },
      { label: 'Gravitace', value: '0,23 m/s²' },
      { label: 'Mateřská planeta', value: 'Saturn' },
      { label: 'Objevitel', value: 'Giovanni Cassini, 1684' },
    ],
    funFact: 'Světlé pruhy na Dione, které z dálky vypadaly jako mraky, jsou ve skutečnosti ledové útesy vysoké stovky metrů.',
  },

  tethys: {
    name: 'Tethys',
    kind: 'moon',
    tagline: 'Saturnův měsíc s obřím kráterem Odysseus.',
    fields: [
      { label: 'Průměr', value: '1 062 km' },
      { label: 'Hmota', value: '6,17×10²⁰ kg' },
      { label: 'Den', value: '1,89 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Saturnu', value: '294 619 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '−187 °C' },
      { label: 'Gravitace', value: '0,15 m/s²' },
      { label: 'Mateřská planeta', value: 'Saturn' },
      { label: 'Objevitel', value: 'Giovanni Cassini, 1684' },
    ],
    funFact: 'Kráter Odysseus má průměr 450 km — dvě pětiny průměru celého Tethyse.',
  },

  enceladus: {
    name: 'Enceladus',
    kind: 'moon',
    tagline: 'Ledový měsíc s gejzíry tekuté vody.',
    fields: [
      { label: 'Průměr', value: '504 km' },
      { label: 'Hmota', value: '1,08×10²⁰ kg' },
      { label: 'Den', value: '1,37 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Saturnu', value: '237 948 km' },
      { label: 'Atmosféra', value: 'vodní pára z gejzírů' },
      { label: 'Povrchová teplota', value: '−198 °C' },
      { label: 'Gravitace', value: '0,11 m/s²' },
      { label: 'Mateřská planeta', value: 'Saturn' },
      { label: 'Objevitel', value: 'William Herschel, 1789' },
    ],
    funFact: 'Enceladus chrlí z jižního pólu gejzíry vody do vesmíru — pod ledem má globální oceán a je horkým kandidátem na život.',
  },

  mimas: {
    name: 'Mimas',
    kind: 'moon',
    tagline: '"Hvězda smrti" díky obřímu kráteru Herschel.',
    fields: [
      { label: 'Průměr', value: '396 km' },
      { label: 'Hmota', value: '3,75×10¹⁹ kg' },
      { label: 'Den', value: '0,94 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Saturnu', value: '185 539 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '−209 °C' },
      { label: 'Gravitace', value: '0,064 m/s²' },
      { label: 'Mateřská planeta', value: 'Saturn' },
      { label: 'Objevitel', value: 'William Herschel, 1789' },
    ],
    funFact: 'Kráter Herschel zabírá třetinu průměru Mimasu a dává mu vzhled jako Death Star ze Star Wars.',
  },

  miranda: {
    name: 'Miranda',
    kind: 'moon',
    tagline: 'Nejmenší a nejdivočejší uranský měsíc.',
    fields: [
      { label: 'Průměr', value: '471 km' },
      { label: 'Hmota', value: '6,59×10¹⁹ kg' },
      { label: 'Den', value: '1,41 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Uranu', value: '129 390 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '−187 °C' },
      { label: 'Gravitace', value: '0,079 m/s²' },
      { label: 'Mateřská planeta', value: 'Uran' },
      { label: 'Objevitel', value: 'Gerard Kuiper, 1948' },
    ],
    funFact: 'Miranda má útes Verona Rupes vysoký 20 km — největší útes sluneční soustavy, skok z něj by trval 12 minut.',
  },

  ariel: {
    name: 'Ariel',
    kind: 'moon',
    tagline: 'Nejsvětlejší uranský měsíc.',
    fields: [
      { label: 'Průměr', value: '1 158 km' },
      { label: 'Hmota', value: '1,35×10²¹ kg' },
      { label: 'Den', value: '2,52 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Uranu', value: '191 020 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '−213 °C' },
      { label: 'Gravitace', value: '0,27 m/s²' },
      { label: 'Mateřská planeta', value: 'Uran' },
      { label: 'Objevitel', value: 'William Lassell, 1851' },
    ],
    funFact: 'Ariel je pokrytý hlubokými údolími z ledu — možná důsledek gravitačního žmoulání, když byl zahřátý.',
  },

  umbriel: {
    name: 'Umbriel',
    kind: 'moon',
    tagline: 'Nejtmavší z hlavních uranských měsíců.',
    fields: [
      { label: 'Průměr', value: '1 169 km' },
      { label: 'Hmota', value: '1,17×10²¹ kg' },
      { label: 'Den', value: '4,14 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Uranu', value: '266 000 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '−198 °C' },
      { label: 'Gravitace', value: '0,23 m/s²' },
      { label: 'Mateřská planeta', value: 'Uran' },
      { label: 'Objevitel', value: 'William Lassell, 1851' },
    ],
    funFact: 'Na Umbrielu je jasný prstencový útvar Wunda — nikdo si není jistý, proč je o tolik světlejší než okolí.',
  },

  titania: {
    name: 'Titania',
    kind: 'moon',
    tagline: 'Největší uranský měsíc.',
    fields: [
      { label: 'Průměr', value: '1 577 km' },
      { label: 'Hmota', value: '3,53×10²¹ kg' },
      { label: 'Den', value: '8,71 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Uranu', value: '435 910 km' },
      { label: 'Atmosféra', value: 'stopová CO₂' },
      { label: 'Povrchová teplota', value: '−203 °C' },
      { label: 'Gravitace', value: '0,37 m/s²' },
      { label: 'Mateřská planeta', value: 'Uran' },
      { label: 'Objevitel', value: 'William Herschel, 1787' },
    ],
    funFact: 'Titania je pojmenována podle královny víl z Shakespearova Snu noci svatojánské — všechny uranské měsíce mají shakespearovská jména.',
  },

  oberon: {
    name: 'Oberon',
    kind: 'moon',
    tagline: 'Nejvzdálenější hlavní uranský měsíc.',
    fields: [
      { label: 'Průměr', value: '1 523 km' },
      { label: 'Hmota', value: '3,01×10²¹ kg' },
      { label: 'Den', value: '13,5 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Uranu', value: '583 520 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Povrchová teplota', value: '−203 °C' },
      { label: 'Gravitace', value: '0,35 m/s²' },
      { label: 'Mateřská planeta', value: 'Uran' },
      { label: 'Objevitel', value: 'William Herschel, 1787' },
    ],
    funFact: 'Na Oberonu byly nalezeny tmavé skvrny neznámého původu — možná stopy dopadů s vysokým obsahem uhlíku.',
  },

  triton: {
    name: 'Triton',
    kind: 'moon',
    tagline: 'Největší Neptunův měsíc — jediný velký měsíc s retrográdní orbitou.',
    fields: [
      { label: 'Průměr', value: '2 707 km' },
      { label: 'Hmota', value: '2,14×10²² kg' },
      { label: 'Den', value: '5,88 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Neptunu', value: '354 800 km' },
      { label: 'Atmosféra', value: 'řídká dusíková (1,4 Pa)' },
      { label: 'Povrchová teplota', value: '−235 °C (jeden z nejstudenějších objektů)' },
      { label: 'Gravitace', value: '0,78 m/s²' },
      { label: 'Mateřská planeta', value: 'Neptun' },
      { label: 'Objevitel', value: 'William Lassell, 1846 (17 dní po objevu Neptunu)' },
    ],
    funFact: 'Triton obíhá retrográdně — opačně, než Neptun rotuje. Pravděpodobně jde o zachycený objekt z Kuiperova pásu, podobný Plutu. Postupně padá na Neptun a za ~3,6 mld let se roztrhá v prstenec.',
  },

  nereid: {
    name: 'Nereid',
    kind: 'moon',
    tagline: 'Měsíc s nejvíce protáhlou orbitou ve sluneční soustavě.',
    fields: [
      { label: 'Průměr', value: '340 km' },
      { label: 'Hmota', value: '~3×10¹⁹ kg' },
      { label: 'Den', value: '~11,5 hodiny' },
      { label: 'Vzdálenost od Neptunu', value: '5 513 400 km (max), 1 372 000 km (min)' },
      { label: 'Excentricita orbity', value: '0,75 (extrém!)' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Mateřská planeta', value: 'Neptun' },
      { label: 'Objevitel', value: 'Gerard Kuiper, 1949' },
    ],
    funFact: 'Nereid se k Neptunu přibližuje na 1,4 mil. km a vzdaluje na 9,7 mil. km — extrémně eliptická dráha. Pravděpodobně byla deformována během zachycení Tritonu.',
  },

  proteus: {
    name: 'Proteus',
    kind: 'moon',
    tagline: 'Druhý největší Neptunův měsíc — temný a nepravidelný.',
    fields: [
      { label: 'Průměr', value: '420 km (nepravidelný tvar)' },
      { label: 'Hmota', value: '~5×10¹⁹ kg' },
      { label: 'Den', value: '1,12 dne (tidálně zamčeno)' },
      { label: 'Vzdálenost od Neptunu', value: '117 647 km' },
      { label: 'Atmosféra', value: 'žádná' },
      { label: 'Albedo', value: '0,096 (jeden z nejtmavších objektů)' },
      { label: 'Mateřská planeta', value: 'Neptun' },
      { label: 'Objevitel', value: 'Voyager 2, 1989' },
    ],
    funFact: 'Proteus byl objeven až sondou Voyager 2 v roce 1989 — z domova nešel pozorovat, je tmavý jako asfalt a blízko Neptunu. Je téměř na hranici, kdy gravitace tělesa stačí ho stáhnout do koule.',
  },
};
