// MOONS — data 22 měsíců.
// Pochopení mode (default): vizuálně srozumitelný — period a eccentricity
//   zveličené ať uživatel vidí orbitální oblouk.
// Fyzikální mode: real astronomická data (`periodReal`, `eReal`).
// `a` = semi-major axis jako násobek parent radius (decorative comp.).
// `phaseOffset` deterministický offset (rad) pro staggered start.

const MOON_TICK = 10242;

export const MOONS = [
  { id: 'luna', name: 'LUNA', parent: 'earth',
    diameterKm: 3474, radiusPx: 2.2, tickCount: MOON_TICK,
    texture: 'textures/luna.jpg',
    a: 2.0, e: 0.275, eReal: 0.0549, period: 20, periodReal: 20, phaseOffset: 0.3,
    realSemiMajorAxisKm: 384_400,
    category: 'moon', inclinationDeg: 5.15,
    dotSize: 1.1, detailDotSize: 0.03 },

  { id: 'phobos', name: 'PHOBOS', parent: 'mars',
    diameterKm: 22, radiusPx: 0.5, tickCount: MOON_TICK,
    texture: 'textures/phobos.jpg',
    a: 1.3, e: 0.1, eReal: 0.0151, period: 2, periodReal: 2, phaseOffset: 0.0,
    realSemiMajorAxisKm: 9_376,
    category: 'moon', inclinationDeg: 1.08,
    shape: { scale: [1.0, 0.81, 0.67], displacement: { type: 'simplex', amplitude: 0.15, seed: 'phobos' } },
    dotSize: 0.35, detailDotSize: 0.008 },
  { id: 'deimos', name: 'DEIMOS', parent: 'mars',
    diameterKm: 12, radiusPx: 0.5, tickCount: MOON_TICK,
    texture: 'textures/deimos.jpg',
    a: 2.0, e: 0.05, eReal: 0.0002, period: 8, periodReal: 7.91, phaseOffset: 1.5,
    realSemiMajorAxisKm: 23_463,
    category: 'moon', inclinationDeg: 1.79,
    shape: { scale: [1.0, 0.80, 0.73], displacement: { type: 'simplex', amplitude: 0.12, seed: 'deimos' } },
    dotSize: 0.35, detailDotSize: 0.008 },

  { id: 'io', name: 'IO', parent: 'jupiter',
    diameterKm: 3643, radiusPx: 2.3, tickCount: MOON_TICK,
    texture: 'textures/io.jpg',
    a: 1.33, e: 0.04, eReal: 0.0041, period: 5, periodReal: 5, phaseOffset: 0.5,
    realSemiMajorAxisKm: 421_700,
    category: 'moon', inclinationDeg: 0.04,
    dotSize: 1.1, detailDotSize: 0.032 },
  { id: 'europa', name: 'EUROPA', parent: 'jupiter',
    diameterKm: 3122, radiusPx: 2.0, tickCount: MOON_TICK,
    texture: 'textures/europa.jpg',
    a: 1.56, e: 0.09, eReal: 0.0094, period: 10, periodReal: 10.04, phaseOffset: 1.2,
    realSemiMajorAxisKm: 671_034,
    category: 'moon', inclinationDeg: 0.47,
    dotSize: 1.0, detailDotSize: 0.028 },
  { id: 'ganymede', name: 'GANYMEDE', parent: 'jupiter',
    diameterKm: 5268, radiusPx: 3.4, tickCount: MOON_TICK,
    texture: 'textures/ganymede.jpg',
    a: 1.78, e: 0.02, eReal: 0.0013, period: 20, periodReal: 20.22, phaseOffset: 2.0,
    realSemiMajorAxisKm: 1_070_400,
    category: 'moon', inclinationDeg: 0.18,
    dotSize: 1.5, detailDotSize: 0.05 },
  { id: 'callisto', name: 'CALLISTO', parent: 'jupiter',
    diameterKm: 4820, radiusPx: 3.1, tickCount: MOON_TICK,
    texture: 'textures/callisto.jpg',
    a: 2.0, e: 0.07, eReal: 0.0074, period: 47, periodReal: 47.16, phaseOffset: 3.5,
    realSemiMajorAxisKm: 1_882_700,
    category: 'moon', inclinationDeg: 0.19,
    dotSize: 1.4, detailDotSize: 0.045 },
  { id: 'sinope', name: 'SINOPE', parent: 'jupiter',
    diameterKm: 38, radiusPx: 1.5, tickCount: 2066,
    category: 'irregular',
    a: 16.0, e: 0.08, eReal: 0.2495, period: 220, periodReal: 758, phaseOffset: 0.4,
    inclinationDeg: 158.1,
    realDiameterKm: 38,
    realSemiMajorAxisKm: 23_939_000,
    color: '#605040',
    texture: null,
    shape: { scale: [1.0, 0.95, 0.9], displacement: { type: 'simplex', amplitude: 0.10, seed: 'sinope' } },
    coverageNote: 'Sinope fotografována jen z dálky. Pravý tvar neznámý.',
    dotSize: 0.35, detailDotSize: 0.008 },
  { id: 'pasiphae', name: 'PASIPHAE', parent: 'jupiter',
    diameterKm: 60, radiusPx: 1.5, tickCount: 2066,
    category: 'irregular',
    a: 15.5, e: 0.08, eReal: 0.4090, period: 200, periodReal: 744, phaseOffset: 1.3,
    inclinationDeg: 151.4,
    realDiameterKm: 60,
    realSemiMajorAxisKm: 23_624_000,
    color: '#554638',
    texture: null,
    shape: { scale: [1.0, 0.92, 0.88], displacement: { type: 'simplex', amplitude: 0.10, seed: 'pasiphae' } },
    coverageNote: 'Pasiphae fotografována jen z dálky. Pravý tvar neznámý.',
    dotSize: 0.35, detailDotSize: 0.008 },

  { id: 'titan', name: 'TITAN', parent: 'saturn',
    diameterKm: 5150, radiusPx: 3.3, tickCount: MOON_TICK,
    texture: 'textures/titan.jpg',
    a: 3.8, e: 0.2, eReal: 0.0288, period: 50, periodReal: 50.79, phaseOffset: 1.8,
    realSemiMajorAxisKm: 1_221_870,
    category: 'moon', inclinationDeg: 0.33,
    dotSize: 1.5, detailDotSize: 0.048 },
  { id: 'rhea', name: 'RHEA', parent: 'saturn',
    diameterKm: 1527, radiusPx: 1.0, tickCount: MOON_TICK,
    texture: 'textures/rhea.jpg',
    a: 3.1, e: 0.02, eReal: 0.001, period: 14.3, periodReal: 14.39, phaseOffset: 0.9,
    realSemiMajorAxisKm: 527_108,
    category: 'moon', inclinationDeg: 0.35,
    dotSize: 0.5, detailDotSize: 0.014 },
  { id: 'iapetus', name: 'IAPETUS', parent: 'saturn',
    diameterKm: 1470, radiusPx: 0.95, tickCount: MOON_TICK,
    texture: 'textures/iapetus.jpg',
    a: 4.4, e: 0.2, eReal: 0.0286, period: 60, periodReal: 252.6, phaseOffset: 2.5,
    realSemiMajorAxisKm: 3_560_820,
    category: 'irregular', inclinationDeg: 14.72,
    dotSize: 0.48, detailDotSize: 0.014 },
  { id: 'dione', name: 'DIONE', parent: 'saturn',
    diameterKm: 1123, radiusPx: 0.72, tickCount: MOON_TICK,
    texture: 'textures/dione.jpg',
    a: 2.9, e: 0.02, eReal: 0.0022, period: 8.7, periodReal: 8.72, phaseOffset: 1.1,
    realSemiMajorAxisKm: 377_396,
    category: 'moon', inclinationDeg: 0.02,
    dotSize: 0.4, detailDotSize: 0.010 },
  { id: 'tethys', name: 'TETHYS', parent: 'saturn',
    diameterKm: 1062, radiusPx: 0.68, tickCount: MOON_TICK,
    texture: 'textures/tethys.jpg',
    a: 2.7, e: 0.02, eReal: 0.0001, period: 6, periodReal: 6.01, phaseOffset: 0.4,
    realSemiMajorAxisKm: 294_619,
    category: 'moon', inclinationDeg: 1.09,
    dotSize: 0.4, detailDotSize: 0.010 },
  { id: 'enceladus', name: 'ENCELADUS', parent: 'saturn',
    diameterKm: 504, radiusPx: 0.5, tickCount: MOON_TICK,
    texture: 'textures/enceladus.jpg',
    a: 2.55, e: 0.05, eReal: 0.0047, period: 4.3, periodReal: 4.36, phaseOffset: 2.2,
    realSemiMajorAxisKm: 237_948,
    category: 'moon', inclinationDeg: 0.02,
    dotSize: 0.35, detailDotSize: 0.008 },
  { id: 'mimas', name: 'MIMAS', parent: 'saturn',
    diameterKm: 396, radiusPx: 0.5, tickCount: MOON_TICK,
    texture: 'textures/mimas.jpg',
    a: 2.4, e: 0.2, eReal: 0.0196, period: 3, periodReal: 3, phaseOffset: 0.1,
    realSemiMajorAxisKm: 185_539,
    category: 'moon', inclinationDeg: 1.57,
    dotSize: 0.35, detailDotSize: 0.008 },
  { id: 'hyperion', name: 'HYPERION', parent: 'saturn',
    diameterKm: 270, radiusPx: 1.5, tickCount: MOON_TICK,
    texture: null, // žádná cylindrická mapa — Cassini foto je orthographic, ne equirectangular
    a: 4.6, e: 0.05, eReal: 0.1230, period: 70, periodReal: 21.28, phaseOffset: 0.7,
    realDiameterKm: 270,
    realSemiMajorAxisKm: 1481010,
    category: 'irregular', inclinationDeg: 0.43,
    color: '#a89478',
    shape: { scale: [1.0, 0.74, 0.57], displacement: { type: 'simplex', amplitude: 0.10, seed: 'hyperion' } },
    chaoticRotation: true,
    coverageNote: 'Cassini close flyby (2005, 2010). Chaotická rotace komplikuje úplné mapování.',
    dotSize: 0.35, detailDotSize: 0.008 },
  { id: 'phoebe', name: 'PHOEBE', parent: 'saturn',
    diameterKm: 213, radiusPx: 1.5, tickCount: MOON_TICK,
    texture: null, // žádná cylindrická mapa — Cassini foto je orthographic, ne equirectangular
    a: 13.5, e: 0.08, eReal: 0.1634, period: 280, periodReal: 550.31, phaseOffset: 2.1,
    realDiameterKm: 213,
    realSemiMajorAxisKm: 12947780,
    category: 'irregular', inclinationDeg: 175.3,
    color: '#7a6650',
    shape: { scale: [1.0, 1.02, 0.94], displacement: { type: 'simplex', amplitude: 0.06, seed: 'phoebe' } },
    coverageNote: 'Phoebe poprvé fotografována Cassini 2004.',
    dotSize: 0.33, detailDotSize: 0.008 },

  { id: 'miranda', name: 'MIRANDA', parent: 'uranus',
    diameterKm: 471, radiusPx: 0.5, tickCount: MOON_TICK,
    texture: 'textures/miranda.jpg',
    a: 1.7, e: 0.02, eReal: 0.0013, period: 4, periodReal: 4, phaseOffset: 1.7,
    realSemiMajorAxisKm: 129_390,
    category: 'moon', inclinationDeg: 4.34,
    coverageNote: 'Druhá strana neviděna od Voyager 2 (1986). Severní hemisféra dosud nenafocena.',
    dotSize: 0.35, detailDotSize: 0.008 },
  { id: 'ariel', name: 'ARIEL', parent: 'uranus',
    diameterKm: 1158, radiusPx: 0.74, tickCount: MOON_TICK,
    texture: 'textures/ariel.jpg',
    a: 1.9, e: 0.02, eReal: 0.0012, period: 7, periodReal: 7.13, phaseOffset: 0.8,
    realSemiMajorAxisKm: 191_020,
    category: 'moon', inclinationDeg: 0.04,
    coverageNote: 'Druhá strana neviděna od Voyager 2 (1986). Severní hemisféra dosud nenafocena.',
    dotSize: 0.4, detailDotSize: 0.011 },
  { id: 'umbriel', name: 'UMBRIEL', parent: 'uranus',
    diameterKm: 1169, radiusPx: 0.75, tickCount: MOON_TICK,
    texture: 'textures/umbriel.jpg',
    a: 2.15, e: 0.04, eReal: 0.0039, period: 12, periodReal: 11.73, phaseOffset: 2.7,
    realSemiMajorAxisKm: 266_000,
    category: 'moon', inclinationDeg: 0.13,
    coverageNote: 'Druhá strana neviděna od Voyager 2 (1986). Severní hemisféra dosud nenafocena.',
    dotSize: 0.4, detailDotSize: 0.011 },
  { id: 'titania', name: 'TITANIA', parent: 'uranus',
    diameterKm: 1577, radiusPx: 1.01, tickCount: MOON_TICK,
    texture: 'textures/titania.jpg',
    a: 2.5, e: 0.02, eReal: 0.0011, period: 25, periodReal: 24.65, phaseOffset: 3.0,
    realSemiMajorAxisKm: 435_910,
    category: 'moon', inclinationDeg: 0.08,
    coverageNote: 'Druhá strana neviděna od Voyager 2 (1986). Severní hemisféra dosud nenafocena.',
    dotSize: 0.5, detailDotSize: 0.014 },
  { id: 'oberon', name: 'OBERON', parent: 'uranus',
    diameterKm: 1523, radiusPx: 0.98, tickCount: MOON_TICK,
    texture: 'textures/oberon.jpg',
    a: 2.8, e: 0.02, eReal: 0.0014, period: 38, periodReal: 38.12, phaseOffset: 0.6,
    realSemiMajorAxisKm: 583_520,
    category: 'moon', inclinationDeg: 0.07,
    coverageNote: 'Druhá strana neviděna od Voyager 2 (1986). Severní hemisféra dosud nenafocena.',
    dotSize: 0.5, detailDotSize: 0.014 },

  // Neptune moony.
  { id: 'triton', name: 'TRITON', parent: 'neptune',
    diameterKm: 2707, radiusPx: 1.74, tickCount: MOON_TICK,
    texture: 'textures/triton.jpg',
    a: 1.5, e: 0.001, eReal: 0.000016, period: 6, periodReal: 6, phaseOffset: 0.2,
    realSemiMajorAxisKm: 354_800,
    category: 'irregular', inclinationDeg: 157.0,
    coverageNote: 'Severní hemisféra neviděna — Voyager 2 (1989) zachytil pouze jižní stranu.',
    dotSize: 0.9, detailDotSize: 0.025 },
  { id: 'nereid', name: 'NEREID', parent: 'neptune',
    diameterKm: 340, radiusPx: 0.5, tickCount: MOON_TICK,
    texture: 'textures/nereid.jpg',
    a: 5.0, e: 0.3, eReal: 0.7507, period: 36, periodReal: 367.7, phaseOffset: 1.5,
    realSemiMajorAxisKm: 5_513_400,
    category: 'irregular', inclinationDeg: 5.0,
    shape: { scale: [1.0, 0.9, 0.85], displacement: { type: 'simplex', amplitude: 0.08, seed: 'nereid' } },
    coverageNote: 'Pouze flyby Voyager 2 (1989). Žádný globální mapový snímek neexistuje.',
    dotSize: 0.3, detailDotSize: 0.007 },
  { id: 'proteus', name: 'PROTEUS', parent: 'neptune',
    diameterKm: 420, radiusPx: 0.5, tickCount: MOON_TICK,
    texture: 'textures/proteus.jpg',
    a: 1.2, e: 0.005, eReal: 0.000534, period: 1.1, periodReal: 1.15, phaseOffset: 0.8,
    realSemiMajorAxisKm: 117_647,
    category: 'moon', inclinationDeg: 0.04,
    shape: { scale: [1.0, 0.99, 0.96], displacement: { type: 'simplex', amplitude: 0.05, seed: 'proteus' } },
    coverageNote: 'Pouze flyby Voyager 2 (1989). Žádný globální mapový snímek neexistuje.',
    dotSize: 0.32, detailDotSize: 0.008 },
];

export const MOON_BY_ID = Object.fromEntries(MOONS.map(m => [m.id, m]));

export const MOONS_BY_PARENT = MOONS.reduce((acc, m) => {
  (acc[m.parent] ??= []).push(m);
  return acc;
}, {});
