// PLANETS — data všech 9 těles V1 (solar wind architecture).
// Referenční měřítko: Jupiter = 180 px průměr.
// rotationPeriod v sekundách (reálné poměry, Země = 10 s).
// direction: 1 = prograde, -1 = retrograde.
// xPosition = horizontální pozice středu v scene units.
// tickCount = počet teček na povrchu (solar wind → destination).

export const PLANETS = [
  {
    id: 'sun',
    name: 'SLUNCE',
    realDiameterKm: 1392700,
    radiusPx: 995.5,
    texture: 'textures/sun.jpg',
    emissive: true,
    tickCount: 18000,         // initial fill (nebude dostávat proud)
    axialTilt: 7.25,
    rotationPeriod: 250,
    direction: 1,
    xPosition: -1500,
    color: 0xffd966,
    realDistanceFromSunKm: 0,
    dotSize: 30,
    detailDotSize: 50,
  },
  {
    id: 'mercury',
    name: 'MERKUR',
    realDiameterKm: 4879,
    radiusPx: 3.15,
    texture: 'textures/mercury.jpg',
    emissive: false,
    tickCount: 2500,
    axialTilt: 0.03,
    rotationPeriod: 586,
    direction: 1,
    xPosition: -390,
    color: 0x8c7853,
    realDistanceFromSunKm: 57_909_000,
    dotSize: 2.5,
    detailDotSize: 0.2,
  },
  {
    id: 'venus',
    name: 'VENUŠE',
    realDiameterKm: 12104,
    radiusPx: 7.8,
    texture: 'textures/venus.jpg',
    emissive: false,
    tickCount: 5000,
    axialTilt: 177.4,
    rotationPeriod: 2430,
    direction: -1,
    xPosition: -340,
    color: 0xe7c98f,
    realDistanceFromSunKm: 108_209_000,
    dotSize: 2.8,
    detailDotSize: 0.5,
  },
  {
    id: 'earth',
    name: 'ZEMĚ',
    realDiameterKm: 12742,
    radiusPx: 8.2,
    texture: 'textures/earth.jpg',
    emissive: false,
    tickCount: 5500,
    axialTilt: 23.44,
    rotationPeriod: 10,
    direction: 1,
    xPosition: -290,
    color: 0x3a84d4,
    realDistanceFromSunKm: 149_598_000,
    dotSize: 2.8,
    detailDotSize: 0.55,
  },
  {
    id: 'mars',
    name: 'MARS',
    realDiameterKm: 6779,
    radiusPx: 4.35,
    texture: 'textures/mars.jpg',
    emissive: false,
    tickCount: 3500,
    axialTilt: 25.19,
    rotationPeriod: 10.25,
    direction: 1,
    xPosition: -245,
    color: 0xc1440e,
    realDistanceFromSunKm: 227_944_000,
    dotSize: 2.5,
    detailDotSize: 0.3,
  },
  {
    id: 'jupiter',
    name: 'JUPITER',
    realDiameterKm: 139820,
    radiusPx: 90,
    texture: 'textures/jupiter.jpg',
    emissive: false,
    tickCount: 8000,
    alpha: 0.72,
    axialTilt: 3.13,
    rotationPeriod: 4.1,
    direction: 1,
    xPosition: -100,
    color: 0xd8c185,
    realDistanceFromSunKm: 778_340_000,
    dotSize: 6.0,
    detailDotSize: 4.5,
  },
  {
    id: 'saturn',
    name: 'SATURN',
    realDiameterKm: 116460,
    radiusPx: 75,
    texture: 'textures/saturn.jpg',
    ringTexture: 'textures/saturn_ring.png',
    ringInnerRadius: 90,
    ringOuterRadius: 175,
    ringTickCount: 5000,
    emissive: false,
    tickCount: 6500,
    alpha: 0.72,
    axialTilt: 26.73,
    rotationPeriod: 4.5,
    direction: 1,
    xPosition: 180,
    color: 0xe3c07a,
    realDistanceFromSunKm: 1_426_666_000,
    dotSize: 5.5,
    detailDotSize: 3.8,
  },
  {
    id: 'uranus',
    name: 'URAN',
    realDiameterKm: 50724,
    radiusPx: 32.5,
    texture: 'textures/uranus.jpg',
    emissive: false,
    tickCount: 4500,
    axialTilt: 97.77,
    rotationPeriod: 7.2,
    direction: -1,
    xPosition: 470,
    color: 0x9fd8e3,
    realDistanceFromSunKm: 2_870_658_000,
    dotSize: 4.0,
    detailDotSize: 1.6,
  },
  {
    id: 'neptune',
    name: 'NEPTUN',
    realDiameterKm: 49244,
    radiusPx: 31.5,
    texture: 'textures/neptune.jpg',
    emissive: false,
    tickCount: 4500,
    axialTilt: 28.32,
    rotationPeriod: 6.7,
    direction: 1,
    xPosition: 570,
    color: 0x3b5ff7,
    realDistanceFromSunKm: 4_498_396_000,
    dotSize: 4.0,
    detailDotSize: 1.6,
  },
];

export const PLANET_BY_ID = Object.fromEntries(PLANETS.map(p => [p.id, p]));

// Celkový pool size pro ParticlePool (sun + planety + ringy + rezerva na labely/in-flight).
export const POOL_SIZE = 72000;

// Kolik teček z proudu každé planety tvoří její label (odbočují nad planetou, drží, pak padnou na surface).
export const LABEL_TICK_COUNT = 250;
